name: Build .NET APP

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ToDoList
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./ToDoList
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ToDoList
